parameters:
  # dump the Service Container into a Single File
  app_db: "%env(string:DATABASE_URL)%"
doctrine:
  dbal:
    # url: '%app_db%'
    # local
     url: 'mysql://rooti:rooti@127.0.0.1:3306/jj-software?serverVersion=mariadb-10.6.3'
    # software auf zoe erver
    # url: "mysql://dbu2609300:KeinerWieEiner23@db5011719954.hosting-data.io:3306/dbs9874848?serverVersion=mariadb-10.6.5"
    # zoe_app
    # url: "mysql://dbu2845907:ic2kzycwC!UYGfb@db5011639230.hosting-data.io:3306/dbs9810606?serverVersion=mariadb-10.6.5"